# Generated by Django 4.1.13 on 2026-02-02 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branchapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tblEmployee',
        ),
    ]
