# Generated by Django 4.1.13 on 2026-02-02 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdminApp', '0006_tbl_shift'),
        ('HomeApp', '0003_remove_tbl_employee_branch_remove_tbl_employee_login_and_more'),
        ('branchapp', '0002_delete_tblemployee'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblEmployee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_code', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('joining_date', models.DateField()),
                ('salary_type', models.CharField(choices=[('monthly', 'Monthly'), ('daily', 'Daily')], max_length=10)),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='AdminApp.tbl_branch')),
                ('designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='AdminApp.tbl_designation')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='HomeApp.tbl_login')),
            ],
        ),
    ]
