# Generated by Django 4.1.13 on 2026-02-04 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0006_tbl_shift'),
        ('branchapp', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblemployee',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='AdminApp.tbl_designation'),
        ),
        migrations.AlterField(
            model_name='tblemployee',
            name='employee_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='tbl_ShiftSchedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('schedule_name', models.CharField(max_length=200)),
                ('period', models.CharField(choices=[('first_half', '1st - 15th'), ('second_half', '16th - 30th/31st')], max_length=20)),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('active', 'Active'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to='AdminApp.tbl_manager')),
            ],
            options={
                'ordering': ['-year', '-month', 'period'],
                'unique_together': {('period', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='tbl_ShiftAssignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='branchapp.tblemployee')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='branchapp.tbl_shiftschedule')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='AdminApp.tbl_shift')),
            ],
            options={
                'ordering': ['schedule', 'employee'],
                'unique_together': {('schedule', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='tbl_DailyAttendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_date', models.DateField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('present', 'Present'), ('absent', 'Absent'), ('on_leave', 'On Leave'), ('holiday', 'Holiday'), ('week_off', 'Week Off')], default='scheduled', max_length=20)),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('late_minutes', models.PositiveIntegerField(default=0)),
                ('early_departure_minutes', models.PositiveIntegerField(default=0)),
                ('overtime_minutes', models.PositiveIntegerField(default=0)),
                ('total_working_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('remarks', models.TextField(blank=True)),
                ('is_holiday', models.BooleanField(default=False)),
                ('is_week_off', models.BooleanField(default=False)),
                ('shift_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='branchapp.tbl_shiftassignment')),
            ],
            options={
                'ordering': ['attendance_date'],
                'unique_together': {('shift_assignment', 'attendance_date')},
            },
        ),
    ]
