# Generated by Django 4.1.13 on 2026-03-06 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branchapp', '0005_tbl_payrollsettings_tbl_attendanceimportlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Payroll',
            fields=[
                ('payroll_id', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_type', models.CharField(max_length=10)),
                ('total_days', models.PositiveIntegerField(default=0)),
                ('present_days', models.PositiveIntegerField(default=0)),
                ('absent_days', models.PositiveIntegerField(default=0)),
                ('leave_days', models.PositiveIntegerField(default=0)),
                ('holidays', models.PositiveIntegerField(default=0)),
                ('absent_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='branchapp.tblemployee')),
            ],
            options={
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
        migrations.RemoveField(
            model_name='tbl_attendanceimportlog',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='tbl_attendanceimportlog',
            name='uploaded_by',
        ),
        migrations.AlterUniqueTogether(
            name='tbl_dailyattendance',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tbl_dailyattendance',
            name='shift_assignment',
        ),
        migrations.RemoveField(
            model_name='tbl_payrollsettings',
            name='branch',
        ),
        migrations.AlterUniqueTogether(
            name='tbl_salarycalculation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tbl_salarycalculation',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='tbl_salarycalculation',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='tbl_salarycalculation',
            name='calculated_by',
        ),
        migrations.RemoveField(
            model_name='tbl_salarycalculation',
            name='employee',
        ),
        migrations.DeleteModel(
            name='tbl_Attendance',
        ),
        migrations.DeleteModel(
            name='tbl_AttendanceImportLog',
        ),
        migrations.DeleteModel(
            name='tbl_DailyAttendance',
        ),
        migrations.DeleteModel(
            name='tbl_PayrollSettings',
        ),
        migrations.DeleteModel(
            name='tbl_SalaryCalculation',
        ),
    ]
