# Generated by Django 4.1.13 on 2026-03-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branchapp', '0006_tbl_payroll_remove_tbl_attendanceimportlog_branch_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbl_shiftschedule',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='tbl_shiftschedule',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='tblemployee',
            name='employee_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
