# Generated by Django 4.1.13 on 2026-02-13 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdminApp', '0008_tblholiday'),
        ('branchapp', '0004_alter_tblemployee_designation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_type', models.CharField(choices=[('full_day', 'Full Day'), ('half_day', 'Half Day'), ('multiple_days', 'Multiple Days')], max_length=20)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('reviewed_date', models.DateTimeField(blank=True, null=True)),
                ('manager_remarks', models.TextField(blank=True)),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='leave_documents/')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to='AdminApp.tbl_manager')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='branchapp.tblemployee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='AdminApp.tblleavetype')),
            ],
            options={
                'db_table': 'tbl_leave_request',
                'ordering': ['-applied_date'],
            },
        ),
        migrations.CreateModel(
            name='tbl_LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casual_leave_total', models.PositiveIntegerField(default=12)),
                ('casual_leave_used', models.PositiveIntegerField(default=0)),
                ('sick_leave_total', models.PositiveIntegerField(default=10)),
                ('sick_leave_used', models.PositiveIntegerField(default=0)),
                ('earned_leave_total', models.PositiveIntegerField(default=30)),
                ('earned_leave_used', models.PositiveIntegerField(default=0)),
                ('year', models.PositiveIntegerField(default=2024)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balance', to='branchapp.tblemployee')),
            ],
            options={
                'db_table': 'tbl_leave_balance',
                'unique_together': {('employee', 'year')},
            },
        ),
    ]
