# Generated by Django 4.1.13 on 2026-01-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_branch',
            name='status',
            field=models.CharField(default='Active', max_length=25),
        ),
    ]
