# Generated by Django 4.1.13 on 2026-01-15 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0003_remove_tbl_employee_branch_remove_tbl_employee_login_and_more'),
        ('AdminApp', '0002_tbl_branch_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Manager',
            fields=[
                ('manager_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeApp.tbl_login')),
            ],
        ),
    ]
