# Generated by Django 4.1.13 on 2026-01-15 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_tbl_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_manager',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.tbl_branch'),
            preserve_default=False,
        ),
    ]
