# Generated by Django 4.1.13 on 2026-01-16 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0005_tbl_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_name', models.CharField(max_length=100, unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('allowed_late_minutes', models.PositiveIntegerField(help_text='Grace time in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
