# Generated by Django 4.1.13 on 2026-02-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0006_tbl_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblLeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_name', models.CharField(max_length=100)),
                ('max_days', models.PositiveIntegerField()),
            ],
        ),
    ]
