# Generated by Django 4.1.13 on 2026-02-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0007_tblleavetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_name', models.CharField(max_length=150)),
                ('holiday_date', models.DateField()),
                ('holiday_type', models.CharField(choices=[('National', 'National'), ('Festival', 'Festival'), ('Company', 'Company')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
