# Generated by Django 4.1.13 on 2026-01-15 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0002_tbl_branch_tbl_manager_tbl_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_employee',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='tbl_employee',
            name='login',
        ),
        migrations.RemoveField(
            model_name='tbl_manager',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='tbl_manager',
            name='login',
        ),
        migrations.DeleteModel(
            name='tbl_branch',
        ),
        migrations.DeleteModel(
            name='tbl_employee',
        ),
        migrations.DeleteModel(
            name='tbl_manager',
        ),
    ]
